<?php

namespace App\Constants;

class AddressNames
{
    public const CITY_NAMES
        = [
            'Hồ Chí Minh',
            'Hà Nội',
            'Đà Nẵng',
            'Hải Phòng',
            'Cần Thơ',
            'Nha Trang',
            'Huế',
            'Vũng Tàu',
            'Buôn Ma Thuột',
            'Vinh',
            'Thủ Dầu Một',
            'Châu Đốc',
            'Đà Lạt',
            'Quy Nhơn',
            'Phan Thiết',
            'Đồng Hới',
            'Long Xuyên',
            'Rạch Giá',
            'Tuy Hòa',
        ];

    public const DISTRICT_NAMES
        = [
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            'Bình Tân',
            'Bình Thạnh',
            'Gò Vấp',
            'Phú Nhuận',
            'Tân Bình',
            'Tân Phú',
            'Nam Từ Liêm',
            'Hà Đông',
            'Bắc Từ Liêm',
            'Tây Hồ',
            'Cầu Giấy',
            'Đống Đa',
            'Hai Bà Trưng',
            'Hoàn Kiếm',
            'Hoàng Mai',
            'Long Biên',
            'Sơn Trà',
            'Ngũ Hành Sơn',
            'Liên Chiểu',
            'Thanh Khê',
            'Hải Châu',
        ];

    public const WARD_NAMES
        = [
            'Phú Hòa',
            'Phú Thọ',
            'Phú Thạnh',
            'Phú Cường',
            'Phú Lợi',
            'Phú Hưng',
            'Phú Mỹ',
            'Hoa Phú',
            'Hoa Phong',
            'Hoa Lư',
            'Hoa Hiệp',
            'Hoa Thạnh',
            'Hoa An',
            'Hoa Tiến',
            'Hoa Hưng',
            'Hoa Sơn',
            'Xuân Phú',
            'Xuân Thọ',
            'Xuân Thành',
            'Xuân Thới',
            'Xuân Thới Đông',
            'Xuân Thới Sơn',
            'Xuân Thới Thượng',
            'Tân Phú',
            'Tân Thạnh',
            'Tân Thới',
            'Tân Thới Hiệp',
            'Tân Thới Nhì',
            'Tân Thới Trung',
            'Tân Thới Tây',
            'Tân Hưng',
            'Tân Lập',
            'Tân Hiệp',
            'Tân Bình',
            'Tân Phong',
            'Tân Quý',
            'Tân Thành',
            'Tân Trung',
            'Tân Xuân',
            'An Phú',
            'An Thạnh',
            'An Hòa',
            'An Lợi Đông',
            'An Lợi Tây',
            'An Bình',
            'An Cư',
            'An Nghĩa',
            'Từ Phú',
            'Từ Thọ',
            'Từ Thạnh',
            'Từ Cường',
            'Vinh Phú',
            'Vinh Thọ',
            'Vinh Thành',
            'Vinh Thới',
            'Vinh Lợi',
            'Vinh Hưng',
            'Vinh Mỹ',
            'Vinh An',
            'Vinh Tiến',
            'Hải Châu',
            'Hải Thành',
            'Hải Thạnh',
        ];
}
